on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 0 * * *'

name: Fluxo de Automatização

jobs:
  MeuRobo:
    runs-on: ubuntu-22.04

    env:
      USER: ${{ secrets.RSCONNECT_USER }}
      TOKEN: ${{ secrets.RSCONNECT_TOKEN }}
      SECRET: ${{ secrets.RSCONNECT_SECRET }}

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar o R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - name: Instalar pacotes de R
        uses: r-lib/actions/setup-renv@v2

      - name: Atualizar dados
        run: |
          source("inflacao/R/etl.R")
        shell: Rscript {0}

      - name: Publicar dashboard
        run: |
          install.packages("rsconnect")
          rsconnect::setAccountInfo(
            name = '${{ env.USER }}',
            token = '${{ env.TOKEN }}',
            secret = '${{ env.SECRET }}'
            )
          rsconnect::deployApp(appDir = "dash_inflacao", forceUpdate = TRUE)
        shell: Rscript {0}

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Atualização de dados e deploy automático